[pytest]
testpaths = tests

[tox]
isolated_build = True
envlist =
  py{38, 39, 310, 311, 312, 313, 314}-pytestlatest
  py311-pytest{62,main}

[testenv]
deps = 
    pytest62: pytest==6.2.5
    pytestmain: git+https://github.com/pytest-dev/pytest.git

commands = pytest {posargs:tests}
description = Run pytest
